In [21]:
import pandas as pd
import os
import numpy as np
a=['./data/'+i for i in os.listdir('./data/')]

In [22]:
columns_to_drop = [
    'src_ip',
    'dst_ip',
    'dst_port',
    'src_port',
    'timestamp',
    'fwd_psh_flags',
    'bwd_psh_flags',
    'fwd_urg_flags',
    'bwd_urg_flags',
    'flow_byts_s', 
    'flow_pkts_s', 
]

In [23]:
df_dataset=pd.DataFrame()
for i in a:
    df_dat=pd.read_csv(i)
    if i =='./data/BENIGN.csv' or './data/BENIGN1.csv':
        df_dat['Label']=0
    if i =='./data/http.csv':
        df_dat['Label']=1
    if i =='./data/udp.csv':
        df_dat['Label']=2
    
    df_dataset=df_dataset.append(df_dat,ignore_index=True)
df_dataset = df_dataset.drop(columns=columns_to_drop)
df_dataset

/tmp/ipykernel_4901/3993244496.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_dataset=df_dataset.append(df_dat,ignore_index=True)
/tmp/ipykernel_4901/3993244496.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_dataset=df_dataset.append(df_dat,ignore_index=True)
/tmp/ipykernel_4901/3993244496.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_dataset=df_dataset.append(df_dat,ignore_index=True)
/tmp/ipykernel_4901/3993244496.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_dataset=df_dataset.append(df_dat,ignore_index=True)

,src_port,protocol,flow_duration,fwd_pkts_s,bwd_pkts_s,tot_fwd_pkts,tot_bwd_pkts,totlen_fwd_pkts,totlen_bwd_pkts,fwd_pkt_len_max,...,fwd_blk_rate_avg,bwd_blk_rate_avg,fwd_seg_size_avg,bwd_seg_size_avg,cwe_flag_count,subflow_fwd_pkts,subflow_bwd_pkts,subflow_fwd_byts,subflow_bwd_byts,Label
0,58967,17,1.140009e+08,12.552533,0.000000,1431,0,2166534,0,1514.0,...,18477.328733,0.0,1514.0,0.0,0,1431,0,2166534,0,2
1,44411,17,1.140106e+08,12.884763,0.000000,1469,0,2224066,0,1514.0,...,18966.371560,0.0,1514.0,0.0,0,1469,0,2224066,0,2
2,33947,17,1.139312e+08,13.060518,0.000000,1488,0,2252832,0,1514.0,...,19225.082176,0.0,1514.0,0.0,0,1488,0,2252832,0,2
3,54504,17,1.140175e+08,12.971698,0.000000,1479,0,2239206,0,1514.0,...,19094.339530,0.0,1514.0,0.0,0,1479,0,2239206,0,2
4,38609,17,1.140171e+08,12.533203,0.000000,1429,0,2163506,0,1514.0,...,18448.875101,0.0,1514.0,0.0,0,1429,0,2163506,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2234,45060,6,9.320000e+02,4291.845494,5364.806867,4,5,432,328,226.0,...,0.000000,0.0,108.0,65.6,0,4,5,432,328,1
2235,45072,6,9.130000e+02,4381.161008,4381.161008,4,4,432,274,226.0,...,0.000000,0.0,108.0,68.5,0,4,4,432,274,1
2236,45080,6,9.190000e+02,4352.557127,4352.557127,4,4,432,274,226.0,...,0.000000,0.0,108.0,68.5,0,4,4,432,274,1
2237,45096,6,9.050000e+02,5524.861878,5524.861878,5,5,498,328,226.0,...,0.000000,0.0,99.6,65.6,0,5,5,498,328,1
2238,45110,6,2.355000e+03,1698.513800,2123.142251,4,5,432,340,226.0,...,0.000000,0.0,108.0,68.0,0,4,5,432,340,1

In [24]:
list(df_dataset["Label"].unique())

[2, 0, 1]

In [25]:
df_dataset.to_csv('live_dat.csv',index=False)